
# ! needed to keep the order of the line !


# 1 colors
BG = (255,255,255)
BLACK = (0,0,0)
GREEN = (0, 255, 0)
BLUE = (0, 0, 128)

# 2 screen
SCREEN_WIDTH = 1000
SCREEN_HEIGHT = 1000



# 3 floor
FLOOR_WIDTH = 180

FLOOR_HEIGHT = 60
LINE_DIFF = 7
START_X_POS_FLOOR = 20 
ZERO_FLOOR = SCREEN_HEIGHT - FLOOR_HEIGHT
NUM_FLOORS = 12
NUM_LINE = NUM_FLOORS - 1
SEC_FOR_FLOOR = .5
PIX_PER_SEC = FLOOR_HEIGHT / SEC_FOR_FLOOR 
IMG_FLOOR = "building.png"

# 4 button
SIZE_BUTTON = int(FLOOR_HEIGHT / 3)
SIZE_BUTTON_NUM = SIZE_BUTTON

X_START_POS_BUTTON = (FLOOR_WIDTH  + START_X_POS_FLOOR) /2
MID_Y_POS = FLOOR_HEIGHT/3


X_END_POS_BUTTEN = X_START_POS_BUTTON + SIZE_BUTTON 
X_START_POS_BUTTEN_CLICK = X_START_POS_BUTTON - (SIZE_BUTTON)
COL_BUTTON_ON = GREEN
COL_BUTTON_OFF = BLACK


# 5 Timer floor
X_POS_TIMER = X_START_POS_BUTTON + SIZE_BUTTON + 15

# elevator

START_X_POS_ELV = START_X_POS_FLOOR + FLOOR_WIDTH +10
ELV_WIDTH = 50
ELV_HEIGHT = FLOOR_HEIGHT -10

DIFF_ELV = ELV_WIDTH 
NUM_ELV = 3
IMG_ELV = "elv.png"
MP3 = "ding.mp3"
PUSE = 2

 


# 5 roof
UP_VERTICE = ZERO_FLOOR - (FLOOR_HEIGHT * NUM_FLOORS  )
LEFT_RUGHT_Y_VERTICE = ZERO_FLOOR - (FLOOR_HEIGHT * (NUM_FLOORS -1) )
if UP_VERTICE < 0:
    UP_VERTICE = 0
roof_vertices = [(((START_X_POS_FLOOR + FLOOR_WIDTH)/2), UP_VERTICE), (START_X_POS_FLOOR, LEFT_RUGHT_Y_VERTICE), (START_X_POS_FLOOR + FLOOR_WIDTH, LEFT_RUGHT_Y_VERTICE)]


